-- ============================================================
-- BusinessHub Pro — Supabase Migration
-- Run this once in Supabase Dashboard → SQL Editor
-- ============================================================

-- ── Users table: add missing columns ────────────────────────
ALTER TABLE public."User"
  ADD COLUMN IF NOT EXISTS loyalty_points  INTEGER      DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_visits    INTEGER      DEFAULT 0,
  ADD COLUMN IF NOT EXISTS avatar_url      TEXT,
  ADD COLUMN IF NOT EXISTS updated_at      TIMESTAMPTZ  DEFAULT NOW();

-- ── Feedback table ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public."Feedback" (
  id              UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         UUID          NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  rating          INTEGER       NOT NULL CHECK (rating BETWEEN 1 AND 5),
  category        TEXT          NOT NULL,
  message         TEXT          NOT NULL,
  points_awarded  INTEGER       DEFAULT 50,
  created_at      TIMESTAMPTZ   DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS feedback_user_id_idx   ON public."Feedback"(user_id);
CREATE INDEX IF NOT EXISTS feedback_created_at_idx ON public."Feedback"(created_at DESC);

-- RLS for Feedback
ALTER TABLE public."Feedback" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can insert own feedback" ON public."Feedback";
CREATE POLICY "Users can insert own feedback"
  ON public."Feedback" FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view own feedback" ON public."Feedback";
CREATE POLICY "Users can view own feedback"
  ON public."Feedback" FOR SELECT
  USING (auth.uid() = user_id);

-- ── Transactions table ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS public."Transactions" (
  id               UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  transaction_id   TEXT         NOT NULL UNIQUE,   -- e.g. TXN-AB12CD34-LX9KM2Z-F7Q2
  user_id          UUID         NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  payment_method   TEXT         NOT NULL CHECK (payment_method IN ('easypaisa', 'jazzcash', 'bank')),
  amount           NUMERIC(12,2) NOT NULL,
  status           TEXT         NOT NULL DEFAULT 'pending_receipt'
                                CHECK (status IN ('pending_receipt','pending_verification','verified','rejected')),
  receipt_url      TEXT,
  external_txn_id  TEXT,               -- Transaction ID generated by Easypaisa/JazzCash app (from user's receipt)
  notes            TEXT,
  created_at       TIMESTAMPTZ  DEFAULT NOW(),
  updated_at       TIMESTAMPTZ  DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS transactions_user_id_idx    ON public."Transactions"(user_id);
CREATE INDEX IF NOT EXISTS transactions_txn_id_idx     ON public."Transactions"(transaction_id);
CREATE INDEX IF NOT EXISTS transactions_created_at_idx ON public."Transactions"(created_at DESC);

-- RLS for Transactions
ALTER TABLE public."Transactions" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can insert own transactions" ON public."Transactions";
CREATE POLICY "Users can insert own transactions"
  ON public."Transactions" FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view own transactions" ON public."Transactions";
CREATE POLICY "Users can view own transactions"
  ON public."Transactions" FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own transactions" ON public."Transactions";
CREATE POLICY "Users can update own transactions"
  ON public."Transactions" FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ── Storage bucket for receipts ──────────────────────────────
-- Run this ONCE to create the storage bucket
INSERT INTO storage.buckets (id, name, public)
  VALUES ('receipts', 'receipts', true)
  ON CONFLICT (id) DO NOTHING;

-- Storage RLS: allow authenticated users to upload to their own folder
DROP POLICY IF EXISTS "Users upload own receipts" ON storage.objects;
CREATE POLICY "Users upload own receipts"
  ON storage.objects FOR INSERT
  WITH CHECK (
    bucket_id = 'receipts' AND
    auth.uid()::text = (storage.foldername(name))[1]
  );

DROP POLICY IF EXISTS "Public read receipts" ON storage.objects;
CREATE POLICY "Public read receipts"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'receipts');

DROP POLICY IF EXISTS "Users update own receipts" ON storage.objects;
CREATE POLICY "Users update own receipts"
  ON storage.objects FOR UPDATE
  USING (
    bucket_id = 'receipts' AND
    auth.uid()::text = (storage.foldername(name))[1]
  );
